### ISSUE TITLE
Add normalize/clean method

### ISSUE THREAD

**Issue by finnp** [singuerinc/better-dni#36]
Just a suggestion: How about adding a `normalize` function that takes input and cleans it like:

```
normalize('   12 34 56 7 8-z') //=> '12345678Z'
```

**Comment by singuerinc** [comment]
Hi @finnp
I was cleaning stuff in early versions of better-dni, but then I realized that this is out of the scope of this library. At the same time methods like `isValid` needs a normalized string otherwise it fails.

So yes, I will add the `normalize` method in case you need it, but I will keep the "basic" implementation in other methods so it does not impact in performance. What do you think?

**Comment by finnp** [comment]
Sounds great! Yeah, totally makes sense to keep them separated.

**Comment by singuerinc** [comment]
Fixed in #37

**Comment by finnp** [comment]
Thanks ❤️
